version: '3.8'

services:
  # MCP Server Testing Environment
  mcp-server-test:
    image: node:22-alpine
    container_name: mcp-server-test
    working_dir: /app
    volumes:
      - ../ruv-swarm/npm:/app/ruv-swarm
      - .:/app/claude-code-flow
      - ./mcp-test-environment:/app/test-env
    environment:
      - NODE_ENV=test
      - MCP_SERVER_MODE=stdio
      - MCP_TIMEOUT=30000
      - RUST_LOG=debug
    networks:
      - mcp-test-network
    command: >
      sh -c "
        cd /app/ruv-swarm && 
        npm install && 
        npm test -- --testNamePattern='MCP' --verbose &&
        cd /app/test-env &&
        npm install &&
        npm test
      "
    depends_on:
      - mcp-protocol-validator
      - mcp-performance-monitor

  # MCP Protocol Validator
  mcp-protocol-validator:
    image: node:22-alpine
    container_name: mcp-protocol-validator
    working_dir: /app
    volumes:
      - ./mcp-test-environment:/app
    environment:
      - NODE_ENV=test
      - MCP_PROTOCOL_VERSION=2024-11-05
    networks:
      - mcp-test-network
    command: >
      sh -c "
        npm install &&
        node validators/protocol-validator.js
      "

  # MCP Performance Monitor
  mcp-performance-monitor:
    image: node:22-alpine
    container_name: mcp-performance-monitor
    working_dir: /app
    volumes:
      - ./mcp-test-environment:/app
    environment:
      - NODE_ENV=test
      - PERFORMANCE_SAMPLES=100
      - BENCHMARK_ITERATIONS=10
    networks:
      - mcp-test-network
    command: >
      sh -c "
        npm install &&
        node performance/mcp-benchmarks.js
      "

  # MCP Tool Validator (Tests all 27 ruv-swarm MCP tools)
  mcp-tool-validator:
    image: node:22-alpine
    container_name: mcp-tool-validator
    working_dir: /app
    volumes:
      - ../ruv-swarm/npm:/app/ruv-swarm
      - ./mcp-test-environment:/app/test-env
    environment:
      - NODE_ENV=test
      - MCP_TOOL_TIMEOUT=15000
      - VALIDATE_ALL_TOOLS=true
    networks:
      - mcp-test-network
    command: >
      sh -c "
        cd /app/ruv-swarm && 
        npm install && 
        cd /app/test-env &&
        npm install &&
        node validators/tool-validator.js
      "

  # MCP Integration Test
  mcp-integration-test:
    image: node:22-alpine
    container_name: mcp-integration-test
    working_dir: /app
    volumes:
      - ../ruv-swarm/npm:/app/ruv-swarm
      - .:/app/claude-code-flow
      - ./mcp-test-environment:/app/test-env
    environment:
      - NODE_ENV=test
      - INTEGRATION_TEST_TIMEOUT=60000
    networks:
      - mcp-test-network
    command: >
      sh -c "
        cd /app/test-env &&
        npm install &&
        node integration/mcp-integration-tests.js
      "

networks:
  mcp-test-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  mcp-test-data:
    driver: local