apiVersion: v1
kind: Service
metadata:
  name: agentic-flow-service
  namespace: agentic-flow
  labels:
    app: agentic-flow
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: agentic-flow

---
apiVersion: v1
kind: Service
metadata:
  name: agentic-flow-headless
  namespace: agentic-flow
  labels:
    app: agentic-flow
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: agentic-flow