apiVersion: v1
kind: Namespace
metadata:
  name: agentic-flow-operators
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agentswarms.agentic-flow.io
spec:
  group: agentic-flow.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
                minimum: 1
                maximum: 1000
              agentType:
                type: string
                enum: ["coordinator", "executor", "analyzer", "monitor", "specialist"]
              capabilities:
                type: array
                items:
                  type: string
              resources:
                type: object
                properties:
                  cpu:
                    type: string
                  memory:
                    type: string
              scaling:
                type: object
                properties:
                  minReplicas:
                    type: integer
                  maxReplicas:
                    type: integer
                  targetCPU:
                    type: integer
                  targetMemory:
                    type: integer
                  targetAgentLoad:
                    type: integer
          status:
            type: object
            properties:
              phase:
                type: string
              replicas:
                type: integer
              readyReplicas:
                type: integer
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
    additionalPrinterColumns:
    - name: Type
      type: string
      jsonPath: .spec.agentType
    - name: Replicas
      type: integer
      jsonPath: .spec.replicas
    - name: Ready
      type: integer
      jsonPath: .status.readyReplicas
    - name: Phase
      type: string
      jsonPath: .status.phase
  scope: Namespaced
  names:
    plural: agentswarms
    singular: agentswarm
    kind: AgentSwarm
    shortNames:
    - as
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-operator
  namespace: agentic-flow-operators
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-operator
  template:
    metadata:
      labels:
        app: agent-operator
    spec:
      serviceAccountName: agent-operator
      containers:
      - name: operator
        image: agentic-flow/agent-operator:latest
        env:
        - name: WATCH_NAMESPACE
          value: "agentic-flow"
        - name: OPERATOR_NAME
          value: "agent-operator"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-operator
  namespace: agentic-flow-operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-operator
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["agentic-flow.io"]
  resources: ["agentswarms"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["agentic-flow.io"]
  resources: ["agentswarms/status"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agent-operator
subjects:
- kind: ServiceAccount
  name: agent-operator
  namespace: agentic-flow-operators
---
# Example AgentSwarm resource
apiVersion: agentic-flow.io/v1
kind: AgentSwarm
metadata:
  name: executor-swarm
  namespace: agentic-flow
spec:
  replicas: 10
  agentType: executor
  capabilities:
    - "task-execution"
    - "parallel-processing"
    - "resource-management"
  resources:
    cpu: "500m"
    memory: "1Gi"
  scaling:
    minReplicas: 5
    maxReplicas: 50
    targetCPU: 70
    targetMemory: 80
    targetAgentLoad: 20