name: Claude Flow Migration Tests

on:
  push:
    branches: [ main, claude-flow-v2.0.0 ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  basic-tests:
    name: Basic Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run basic tests
        run: npm test
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.os }}-node${{ matrix.node }}
          path: coverage/

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [basic-tests]
    if: always()
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: test-artifacts
      
      - name: Generate test summary
        run: |
          echo "# Claude Flow Test Summary" > test-summary.md
          echo "" >> test-summary.md
          echo "## Test Results" >> test-summary.md
          echo "" >> test-summary.md
          echo "Basic tests completed across all platforms and Node.js versions." >> test-summary.md
          
          cat test-summary.md
      
      - name: Upload test summary
        uses: actions/upload-artifact@v3
        with:
          name: test-summary
          path: test-summary.md